#!/usr/bin/env node
/* QuoteMaster build script
 * Run: node build.js
 * Concatenates all js/ module files into app.js
 */
const fs = require('fs'), vm = require('vm');

const ORDER = [
  'js/core.js','js/mod-dashboard.js','js/mod-products.js','js/mod-stock.js',
  'js/mod-customers.js','js/mod-invoices.js','js/mod-deliveries.js','js/mod-email.js',
  'js/mod-settings.js','js/mod-zakat.js','js/mod-gst.js','js/mod-expenses.js',
  'js/mod-barcode.js','js/mod-employees.js','js/mod-pos.js','js/mod-team.js',
  'js/mod-admin.js','js/mod-upgrade.js','js/mod-orders.js'
];

const bundled = `/* QuoteMaster app.js — generated by build.js. Edit files in js/ then run: node build.js */\n` +
  ORDER.map(f => `\n/* ── MODULE: ${f.replace('js/','').replace('.js','')} ── */\n` + fs.readFileSync(f,'utf8')).join('\n');

try { new vm.Script(bundled); }
catch(e) { console.error('Syntax error:', e.message); process.exit(1); }

fs.writeFileSync('app.js', bundled);
console.log(`✓ app.js built: ${(bundled.length/1024).toFixed(1)}KB from ${ORDER.length} modules`);
